"""Deterministic, broker-independent platform primitives."""

from adaptive_trader.platform.canonical import CanonicalizationError, canonical_json_bytes
from adaptive_trader.platform.config import (
    BrokerAdapter,
    ExecutionMode,
    ExecutionSpec,
    ExperimentConfigError,
    ExperimentDefinition,
    ExperimentHashMismatchError,
    ExperimentSpec,
    MarketDataAdapter,
    MarketDataSpec,
    PaperOrderEnablement,
    PlatformConfig,
    PlatformProfile,
    RiskGroupSpec,
    RiskPolicySpec,
    RuntimeService,
    RuntimeSettings,
    RuntimeSettingsError,
    SessionSpec,
    SignalProviderSpec,
    StoragePolicySpec,
    load_experiment,
    load_platform_config,
    load_runtime_settings,
)
from adaptive_trader.platform.hashing import sha256_hex
from adaptive_trader.platform.security import (
    RedactedSecret,
    SecretFileError,
    SecretFileReference,
    SecretFileVariable,
    load_secret_file,
)
from adaptive_trader.platform.universe import SymbolRole, UniverseSpec

__all__ = [
    "BrokerAdapter",
    "CanonicalizationError",
    "ExecutionMode",
    "ExecutionSpec",
    "ExperimentConfigError",
    "ExperimentDefinition",
    "ExperimentHashMismatchError",
    "ExperimentSpec",
    "MarketDataAdapter",
    "MarketDataSpec",
    "PaperOrderEnablement",
    "PlatformConfig",
    "PlatformProfile",
    "RedactedSecret",
    "RiskGroupSpec",
    "RiskPolicySpec",
    "RuntimeService",
    "RuntimeSettings",
    "RuntimeSettingsError",
    "SecretFileError",
    "SecretFileReference",
    "SecretFileVariable",
    "SessionSpec",
    "SignalProviderSpec",
    "StoragePolicySpec",
    "SymbolRole",
    "UniverseSpec",
    "canonical_json_bytes",
    "load_experiment",
    "load_platform_config",
    "load_runtime_settings",
    "load_secret_file",
    "sha256_hex",
]
