"""Deterministic, broker-independent platform primitives."""

from adaptive_trader.platform.canonical import CanonicalizationError, canonical_json_bytes
from adaptive_trader.platform.config import (
    BrokerAdapter,
    ExecutionMode,
    ExecutionSpec,
    ExperimentConfigError,
    ExperimentDefinition,
    ExperimentHashMismatchError,
    ExperimentSpec,
    MarketDataAdapter,
    MarketDataSpec,
    PaperOrderEnablement,
    PlatformConfig,
    PlatformProfile,
    RiskGroupSpec,
    RiskPolicySpec,
    RuntimeService,
    RuntimeSettings,
    RuntimeSettingsError,
    SessionSpec,
    SignalProviderSpec,
    StoragePolicySpec,
    load_experiment,
    load_platform_config,
    load_runtime_settings,
)
from adaptive_trader.platform.domain import (
    DecimalRounding,
    DeterministicId,
    quantize_decimal,
    require_finite_decimal,
    require_utc_instant,
)
from adaptive_trader.platform.errors import DomainValidationError
from adaptive_trader.platform.hashing import sha256_hex
from adaptive_trader.platform.security import (
    LOCAL_BOOTSTRAP_FILENAMES,
    LocalSecretBootstrapError,
    LocalSecretBootstrapResult,
    RedactedSecret,
    SecretFileError,
    SecretFileReference,
    SecretFileVariable,
    bootstrap_local_secrets,
    load_secret_file,
)
from adaptive_trader.platform.universe import SymbolRole, UniverseSpec

__all__ = [
    "LOCAL_BOOTSTRAP_FILENAMES",
    "BrokerAdapter",
    "CanonicalizationError",
    "DecimalRounding",
    "DeterministicId",
    "DomainValidationError",
    "ExecutionMode",
    "ExecutionSpec",
    "ExperimentConfigError",
    "ExperimentDefinition",
    "ExperimentHashMismatchError",
    "ExperimentSpec",
    "LocalSecretBootstrapError",
    "LocalSecretBootstrapResult",
    "MarketDataAdapter",
    "MarketDataSpec",
    "PaperOrderEnablement",
    "PlatformConfig",
    "PlatformProfile",
    "RedactedSecret",
    "RiskGroupSpec",
    "RiskPolicySpec",
    "RuntimeService",
    "RuntimeSettings",
    "RuntimeSettingsError",
    "SecretFileError",
    "SecretFileReference",
    "SecretFileVariable",
    "SessionSpec",
    "SignalProviderSpec",
    "StoragePolicySpec",
    "SymbolRole",
    "UniverseSpec",
    "bootstrap_local_secrets",
    "canonical_json_bytes",
    "load_experiment",
    "load_platform_config",
    "load_runtime_settings",
    "load_secret_file",
    "quantize_decimal",
    "require_finite_decimal",
    "require_utc_instant",
    "sha256_hex",
]
