"""Fixed bounds shared by deterministic platform domain contracts."""

from __future__ import annotations

from typing import Final

MIN_SIGNED_64_BIT_INTEGER: Final = -(2**63)
MAX_SIGNED_64_BIT_INTEGER: Final = 2**63 - 1
SHA256_HEX_LENGTH: Final = 64
AUDIT_GENESIS_HASH: Final = "0" * SHA256_HEX_LENGTH

MAX_AUDIT_STREAM_ID_LENGTH: Final = 128
MAX_AUDIT_EVENT_TYPE_LENGTH: Final = 64
MAX_AUDIT_ACTOR_LENGTH: Final = 64
MAX_AUDIT_PAYLOAD_BYTES: Final = 65_536
MAX_AUDIT_CONTAINER_ITEMS: Final = 256

MAX_DETERMINISTIC_ID_PREFIX_LENGTH: Final = 32
MAX_DOMAIN_DECIMAL_DIGITS: Final = 64
MIN_DOMAIN_DECIMAL_EXPONENT: Final = -64
MAX_DOMAIN_DECIMAL_EXPONENT: Final = 64
